[package]
name = "analytics"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
criterion = { workspace = true }

[[test]]
name = "err_stab"
path = "tests/err_stab.rs"

[[test]]
name = "time_series"
path = "tests/time_series.rs"

[[bench]]
name = "main"
harness = false
